site_name: Nutrition
nav:
  - Get Started: index.md
  - Controllers:
      - Dataframe: dataframe.md
  - Calculations:
      - Calc: calculation.md
      - Dictonaries: dictionarie.md

theme: readthedocs

plugins:
  - mkdocstrings:
      default_handlers: python
